import {
  Server,
  Database,
  Cloud,
  CloudOff,
  HardDrive,
  Cpu,
  MemoryStick,
  Network,
  Router,
  Wifi,
  WifiOff,
  Container,
  Boxes,
  Layers,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitFork,
  GitCompare,
  Terminal,
  TerminalSquare,
  Code,
  Code2,
  FileCode,
  Braces,
  Binary,
  Workflow,
  Waypoints,
  Lock,
  Unlock,
  LockKeyhole,
  Shield,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  ShieldQuestion,
  Key,
  KeyRound,
  Fingerprint,
  Eye,
  EyeOff,
  AlertTriangle,
  AlertOctagon,
  AlertCircle,
  ScanFace,
  Bug,
  Skull,
  UserCheck,
  UserX,
  Ban,
  Laptop,
  Smartphone,
  Tablet,
  Monitor,
  MonitorSmartphone,
  Watch,
  Printer,
  Keyboard,
  Mouse,
  Gamepad2,
  Camera,
  Headphones,
  Speaker,
  Tv,
  Usb,
  Battery,
  BatteryCharging,
  Plug,
  PlugZap,
  Power,
  Mail,
  MailOpen,
  MailPlus,
  MessageSquare,
  MessageCircle,
  Send,
  Phone,
  PhoneCall,
  PhoneOff,
  Voicemail,
  Bell,
  BellOff,
  BellRing,
  Rss,
  Share2,
  AtSign,
  Hash,
  Megaphone,
  Radio,
  Podcast,
  Video,
  VideoOff,
  Mic,
  MicOff,
  File,
  FileText,
  FilePlus,
  FileMinus,
  FileCheck,
  FileX,
  FileSearch,
  FileSpreadsheet,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderTree,
  Archive,
  ArchiveRestore,
  Download,
  Upload,
  Save,
  Trash2,
  Copy,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Paperclip,
  Link,
  Link2,
  Table,
  BarChart,
  BarChart2,
  PieChart,
  LineChart,
  Layout,
  LayoutGrid,
  LayoutList,
  LayoutDashboard,
  LayoutTemplate,
  PanelLeft,
  PanelRight,
  PanelTop,
  Sidebar,
  Circle,
  Triangle,
  Hexagon,
  Pentagon,
  Diamond,
  Star,
  Heart,
  Bookmark,
  Tag,
  Palette,
  Brush,
  PenTool,
  Pencil,
  Ruler,
  Move,
  Maximize,
  Minimize,
  Crop,
  Frame,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ArrowUpLeft,
  ArrowDownLeft,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  ChevronsRight,
  ChevronsLeft,
  CornerDownRight,
  CornerUpRight,
  Navigation,
  Navigation2,
  Compass,
  MapPin,
  Map,
  Route,
  Milestone,
  Flag,
  Signpost,
  Image,
  Images,
  Film,
  Play,
  Pause,
  Square,
  SkipForward,
  SkipBack,
  Rewind,
  FastForward,
  Volume2,
  VolumeX,
  Volume1,
  Music,
  Music2,
  Disc,
  Aperture,
  Clapperboard,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Wallet,
  DollarSign,
  Receipt,
  Banknote,
  Coins,
  TrendingUp,
  TrendingDown,
  PiggyBank,
  Percent,
  Gift,
  Package,
  PackageCheck,
  Truck,
  Store,
  Handshake,
  Landmark,
  Scale,
  User,
  Users,
  UserPlus,
  UserMinus,
  UserCircle,
  UserCog,
  Contact,
  Baby,
  PersonStanding,
  Accessibility,
  Smile,
  Frown,
  ThumbsUp,
  ThumbsDown,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Droplet,
  Flame,
  Snowflake,
  Umbrella,
  Leaf,
  Trees,
  Mountain,
  Waves,
  Sunrise,
  Sunset,
  Clock,
  Clock3,
  Calendar,
  CalendarDays,
  CalendarCheck,
  CalendarClock,
  Timer,
  Hourglass,
  History,
  AlarmClock,
  CheckCircle,
  XCircle,
  PlusCircle,
  MinusCircle,
  HelpCircle,
  Info,
  Check,
  X,
  Plus,
  Minus,
  Equal,
  Infinity,
  Asterisk,
  Zap,
  ZapOff,
  Activity,
  Target,
  Crosshair,
  Award,
  Trophy,
  Settings,
  Settings2,
  Wrench,
  Hammer,
  Cog,
  Sliders,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  Filter,
  Search,
  ZoomIn,
  ZoomOut,
  RefreshCw,
  RotateCw,
  Undo2,
  Redo2,
  Home,
  Building,
  Building2,
  School,
  Hospital,
  Church,
  Factory,
  Warehouse,
  Globe,
  Anchor,
  Rocket,
  Plane,
  Car,
  Bus,
  Train,
  Bike,
  Ship,
  type LucideIcon,
} from "lucide-react";

export type IconCategory =
  | "Infrastructure & Cloud"
  | "Security"
  | "Devices"
  | "Communication"
  | "Files & Data"
  | "UI & Design"
  | "Arrows & Navigation"
  | "Media"
  | "Commerce & Finance"
  | "People & Users"
  | "Weather & Nature"
  | "Time & Calendar"
  | "Status & Symbols"
  | "Tools & Settings"
  | "Places & Objects";

export const iconCategories: Record<IconCategory, string[]> = {
  "Infrastructure & Cloud": ["server", "database", "cloud", "cloud-off", "hard-drive", "cpu", "memory-stick", "network", "router", "wifi", "wifi-off", "container", "boxes", "layers", "git-branch", "git-commit", "git-merge", "git-pull-request", "git-fork", "git-compare", "terminal", "terminal-square", "code", "code2", "file-code", "braces", "binary", "workflow", "waypoints"],
  "Security": ["lock", "unlock", "lock-keyhole", "shield", "shield-check", "shield-alert", "shield-off", "shield-question", "key", "key-round", "fingerprint", "eye", "eye-off", "alert-triangle", "alert-octagon", "alert-circle", "scan-face", "bug", "skull", "user-check", "user-x", "ban"],
  "Devices": ["laptop", "smartphone", "tablet", "monitor", "monitor-smartphone", "watch", "printer", "keyboard", "mouse", "gamepad2", "camera", "headphones", "speaker", "tv", "usb", "battery", "battery-charging", "plug", "plug-zap", "power"],
  "Communication": ["mail", "mail-open", "mail-plus", "message-square", "message-circle", "send", "phone", "phone-call", "phone-off", "voicemail", "bell", "bell-off", "bell-ring", "rss", "share2", "at-sign", "hash", "megaphone", "radio", "podcast", "video", "video-off", "mic", "mic-off"],
  "Files & Data": ["file", "file-text", "file-plus", "file-minus", "file-check", "file-x", "file-search", "file-spreadsheet", "folder", "folder-open", "folder-plus", "folder-tree", "archive", "archive-restore", "download", "upload", "save", "trash2", "copy", "clipboard", "clipboard-check", "clipboard-list", "paperclip", "link", "link2", "table", "bar-chart", "bar-chart2", "pie-chart", "line-chart"],
  "UI & Design": ["layout", "layout-grid", "layout-list", "layout-dashboard", "layout-template", "panel-left", "panel-right", "panel-top", "sidebar", "circle", "triangle", "hexagon", "pentagon", "diamond", "star", "heart", "bookmark", "tag", "palette", "brush", "pen-tool", "pencil", "ruler", "move", "maximize", "minimize", "crop", "frame"],
  "Arrows & Navigation": ["arrow-right", "arrow-left", "arrow-up", "arrow-down", "arrow-up-right", "arrow-down-right", "arrow-up-left", "arrow-down-left", "chevron-right", "chevron-left", "chevron-up", "chevron-down", "chevrons-right", "chevrons-left", "corner-down-right", "corner-up-right", "navigation", "navigation2", "compass", "map-pin", "map", "route", "milestone", "flag", "signpost"],
  "Media": ["image", "images", "film", "play", "pause", "square", "skip-forward", "skip-back", "rewind", "fast-forward", "volume2", "volume-x", "volume1", "music", "music2", "disc", "aperture", "clapperboard"],
  "Commerce & Finance": ["shopping-cart", "shopping-bag", "credit-card", "wallet", "dollar-sign", "receipt", "banknote", "coins", "trending-up", "trending-down", "piggy-bank", "percent", "gift", "package", "package-check", "truck", "store", "handshake", "landmark", "scale"],
  "People & Users": ["user", "users", "user-plus", "user-minus", "user-circle", "user-cog", "contact", "baby", "person-standing", "accessibility", "smile", "frown", "thumbs-up", "thumbs-down"],
  "Weather & Nature": ["sun", "moon", "cloud-rain", "cloud-snow", "cloud-lightning", "wind", "droplet", "flame", "snowflake", "umbrella", "leaf", "trees", "mountain", "waves", "sunrise", "sunset"],
  "Time & Calendar": ["clock", "clock3", "calendar", "calendar-days", "calendar-check", "calendar-clock", "timer", "hourglass", "history", "alarm-clock"],
  "Status & Symbols": ["check-circle", "x-circle", "plus-circle", "minus-circle", "help-circle", "info", "check", "x", "plus", "minus", "equal", "infinity", "asterisk", "zap", "zap-off", "activity", "target", "crosshair", "award", "trophy"],
  "Tools & Settings": ["settings", "settings2", "wrench", "hammer", "cog", "sliders", "sliders-horizontal", "toggle-left", "toggle-right", "filter", "search", "zoom-in", "zoom-out", "refresh-cw", "rotate-cw", "undo2", "redo2"],
  "Places & Objects": ["home", "building", "building2", "school", "hospital", "church", "factory", "warehouse", "globe", "anchor", "rocket", "plane", "car", "bus", "train", "bike", "ship"],
};

export const iconRegistry: Record<string, LucideIcon> = {
  "server": Server,
  "database": Database,
  "cloud": Cloud,
  "cloud-off": CloudOff,
  "hard-drive": HardDrive,
  "cpu": Cpu,
  "memory-stick": MemoryStick,
  "network": Network,
  "router": Router,
  "wifi": Wifi,
  "wifi-off": WifiOff,
  "container": Container,
  "boxes": Boxes,
  "layers": Layers,
  "git-branch": GitBranch,
  "git-commit": GitCommit,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-fork": GitFork,
  "git-compare": GitCompare,
  "terminal": Terminal,
  "terminal-square": TerminalSquare,
  "code": Code,
  "code2": Code2,
  "file-code": FileCode,
  "braces": Braces,
  "binary": Binary,
  "workflow": Workflow,
  "waypoints": Waypoints,
  "lock": Lock,
  "unlock": Unlock,
  "lock-keyhole": LockKeyhole,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "shield-off": ShieldOff,
  "shield-question": ShieldQuestion,
  "key": Key,
  "key-round": KeyRound,
  "fingerprint": Fingerprint,
  "eye": Eye,
  "eye-off": EyeOff,
  "alert-triangle": AlertTriangle,
  "alert-octagon": AlertOctagon,
  "alert-circle": AlertCircle,
  "scan-face": ScanFace,
  "bug": Bug,
  "skull": Skull,
  "user-check": UserCheck,
  "user-x": UserX,
  "ban": Ban,
  "laptop": Laptop,
  "smartphone": Smartphone,
  "tablet": Tablet,
  "monitor": Monitor,
  "monitor-smartphone": MonitorSmartphone,
  "watch": Watch,
  "printer": Printer,
  "keyboard": Keyboard,
  "mouse": Mouse,
  "gamepad2": Gamepad2,
  "camera": Camera,
  "headphones": Headphones,
  "speaker": Speaker,
  "tv": Tv,
  "usb": Usb,
  "battery": Battery,
  "battery-charging": BatteryCharging,
  "plug": Plug,
  "plug-zap": PlugZap,
  "power": Power,
  "mail": Mail,
  "mail-open": MailOpen,
  "mail-plus": MailPlus,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  "send": Send,
  "phone": Phone,
  "phone-call": PhoneCall,
  "phone-off": PhoneOff,
  "voicemail": Voicemail,
  "bell": Bell,
  "bell-off": BellOff,
  "bell-ring": BellRing,
  "rss": Rss,
  "share2": Share2,
  "at-sign": AtSign,
  "hash": Hash,
  "megaphone": Megaphone,
  "radio": Radio,
  "podcast": Podcast,
  "video": Video,
  "video-off": VideoOff,
  "mic": Mic,
  "mic-off": MicOff,
  "file": File,
  "file-text": FileText,
  "file-plus": FilePlus,
  "file-minus": FileMinus,
  "file-check": FileCheck,
  "file-x": FileX,
  "file-search": FileSearch,
  "file-spreadsheet": FileSpreadsheet,
  "folder": Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  "folder-tree": FolderTree,
  "archive": Archive,
  "archive-restore": ArchiveRestore,
  "download": Download,
  "upload": Upload,
  "save": Save,
  "trash2": Trash2,
  "copy": Copy,
  "clipboard": Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "paperclip": Paperclip,
  "link": Link,
  "link2": Link2,
  "table": Table,
  "bar-chart": BarChart,
  "bar-chart2": BarChart2,
  "pie-chart": PieChart,
  "line-chart": LineChart,
  "layout": Layout,
  "layout-grid": LayoutGrid,
  "layout-list": LayoutList,
  "layout-dashboard": LayoutDashboard,
  "layout-template": LayoutTemplate,
  "panel-left": PanelLeft,
  "panel-right": PanelRight,
  "panel-top": PanelTop,
  "sidebar": Sidebar,
  "circle": Circle,
  "triangle": Triangle,
  "hexagon": Hexagon,
  "pentagon": Pentagon,
  "diamond": Diamond,
  "star": Star,
  "heart": Heart,
  "bookmark": Bookmark,
  "tag": Tag,
  "palette": Palette,
  "brush": Brush,
  "pen-tool": PenTool,
  "pencil": Pencil,
  "ruler": Ruler,
  "move": Move,
  "maximize": Maximize,
  "minimize": Minimize,
  "crop": Crop,
  "frame": Frame,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "arrow-up-right": ArrowUpRight,
  "arrow-down-right": ArrowDownRight,
  "arrow-up-left": ArrowUpLeft,
  "arrow-down-left": ArrowDownLeft,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "chevrons-right": ChevronsRight,
  "chevrons-left": ChevronsLeft,
  "corner-down-right": CornerDownRight,
  "corner-up-right": CornerUpRight,
  "navigation": Navigation,
  "navigation2": Navigation2,
  "compass": Compass,
  "map-pin": MapPin,
  "map": Map,
  "route": Route,
  "milestone": Milestone,
  "flag": Flag,
  "signpost": Signpost,
  "image": Image,
  "images": Images,
  "film": Film,
  "play": Play,
  "pause": Pause,
  "square": Square,
  "skip-forward": SkipForward,
  "skip-back": SkipBack,
  "rewind": Rewind,
  "fast-forward": FastForward,
  "volume2": Volume2,
  "volume-x": VolumeX,
  "volume1": Volume1,
  "music": Music,
  "music2": Music2,
  "disc": Disc,
  "aperture": Aperture,
  "clapperboard": Clapperboard,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
  "wallet": Wallet,
  "dollar-sign": DollarSign,
  "receipt": Receipt,
  "banknote": Banknote,
  "coins": Coins,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "piggy-bank": PiggyBank,
  "percent": Percent,
  "gift": Gift,
  "package": Package,
  "package-check": PackageCheck,
  "truck": Truck,
  "store": Store,
  "handshake": Handshake,
  "landmark": Landmark,
  "scale": Scale,
  "user": User,
  "users": Users,
  "user-plus": UserPlus,
  "user-minus": UserMinus,
  "user-circle": UserCircle,
  "user-cog": UserCog,
  "contact": Contact,
  "baby": Baby,
  "person-standing": PersonStanding,
  "accessibility": Accessibility,
  "smile": Smile,
  "frown": Frown,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  "sun": Sun,
  "moon": Moon,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  "cloud-lightning": CloudLightning,
  "wind": Wind,
  "droplet": Droplet,
  "flame": Flame,
  "snowflake": Snowflake,
  "umbrella": Umbrella,
  "leaf": Leaf,
  "trees": Trees,
  "mountain": Mountain,
  "waves": Waves,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "clock": Clock,
  "clock3": Clock3,
  "calendar": Calendar,
  "calendar-days": CalendarDays,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "timer": Timer,
  "hourglass": Hourglass,
  "history": History,
  "alarm-clock": AlarmClock,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "plus-circle": PlusCircle,
  "minus-circle": MinusCircle,
  "help-circle": HelpCircle,
  "info": Info,
  "check": Check,
  "x": X,
  "plus": Plus,
  "minus": Minus,
  "equal": Equal,
  "infinity": Infinity,
  "asterisk": Asterisk,
  "zap": Zap,
  "zap-off": ZapOff,
  "activity": Activity,
  "target": Target,
  "crosshair": Crosshair,
  "award": Award,
  "trophy": Trophy,
  "settings": Settings,
  "settings2": Settings2,
  "wrench": Wrench,
  "hammer": Hammer,
  "cog": Cog,
  "sliders": Sliders,
  "sliders-horizontal": SlidersHorizontal,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  "filter": Filter,
  "search": Search,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  "refresh-cw": RefreshCw,
  "rotate-cw": RotateCw,
  "undo2": Undo2,
  "redo2": Redo2,
  "home": Home,
  "building": Building,
  "building2": Building2,
  "school": School,
  "hospital": Hospital,
  "church": Church,
  "factory": Factory,
  "warehouse": Warehouse,
  "globe": Globe,
  "anchor": Anchor,
  "rocket": Rocket,
  "plane": Plane,
  "car": Car,
  "bus": Bus,
  "train": Train,
  "bike": Bike,
  "ship": Ship,
};

export const iconNames = Object.keys(iconRegistry);

export function iconLabel(name: string): string {
  return name
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
