import {
  Server,
  Database,
  Cloud,
  User,
  Users,
  Globe,
  Lock,
  Shield,
  Mail,
  Phone,
  Laptop,
  Smartphone,
  Wifi,
  Terminal,
  Code,
  GitBranch,
  Folder,
  File,
  Settings,
  AlertTriangle,
  CheckCircle,
  XCircle,
  ArrowRight,
  Zap,
  Cpu,
  HardDrive,
  Network,
  Key,
  CreditCard,
  ShoppingCart,
  Bell,
  Calendar,
  Clock,
  MapPin,
  Camera,
  Image,
  Video,
  Mic,
  Layers,
  Box,
  type LucideIcon,
} from "lucide-react";

export const iconRegistry: Record<string, LucideIcon> = {
  server: Server,
  database: Database,
  cloud: Cloud,
  user: User,
  users: Users,
  globe: Globe,
  lock: Lock,
  shield: Shield,
  mail: Mail,
  phone: Phone,
  laptop: Laptop,
  smartphone: Smartphone,
  wifi: Wifi,
  terminal: Terminal,
  code: Code,
  "git-branch": GitBranch,
  folder: Folder,
  file: File,
  settings: Settings,
  "alert-triangle": AlertTriangle,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "arrow-right": ArrowRight,
  zap: Zap,
  cpu: Cpu,
  "hard-drive": HardDrive,
  network: Network,
  key: Key,
  "credit-card": CreditCard,
  "shopping-cart": ShoppingCart,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  "map-pin": MapPin,
  camera: Camera,
  image: Image,
  video: Video,
  mic: Mic,
  layers: Layers,
  box: Box,
};

export const iconNames = Object.keys(iconRegistry);

export function iconLabel(name: string): string {
  return name
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
